### ISSUE TITLE
非自己研发的效果，请注明引用来源和原作者

### ISSUE THREAD

**Issue by bilibiliou** [whxaxes/canvas-test#15]
请遵从 创意共享3c 精神，尊重原作者

**Comment by whxaxes** [comment]
怎么叫非自己研发的效果？？？我抄人代码了？？？

**Comment by bilibiliou** [comment]
low poly 图片化 是 @Ovilia 开发 https://github.com/Ovilia/Polyvia

**Comment by whxaxes** [comment]
这些部分 demo 都是几年前我看了他们的博文，然后学习自己开发出来的，我写的博文里基本上都有写从哪里来的创意

**Comment by whxaxes** [comment]
但是代码是我自己写的，实现逻辑都不一定一致，你的意思是，只要我看了哪里的创意都要在代码里注释？

**Comment by Ovilia** [comment]
Polyvia 是 MIT license，理论上的确不需要引用出处。

**Comment by whxaxes** [comment]
@Ovilia 感谢回复，我还是在 reame 上注明一下本 repo 中的 demo 创意均非原创，仅为个人学习之作，免得又有人找……

**Comment by whxaxes** [comment]
![image](https://user-images.githubusercontent.com/5856440/58532399-fce16780-8217-11e9-8d5f-3a72e5919f4e.png)
