### ISSUE TITLE
clip效果如果修改了css里的left或者top，canvas的擦图坐标也错位了

### ISSUE THREAD

**Issue by qianzhangsheng** [whxaxes/canvas-test#3]
clip效果如果修改了css里的left或者top，canvas的擦图坐标也错位了，这个是canvas的局限吗？

**Comment by whxaxes** [comment]
这个只是因为计算擦除坐标点的时候没把包裹canvas的dom的位置也算上而已，我改了一下，算上了外层的位置就可以了

**Comment by qianzhangsheng** [comment]
麻烦大神啦
