### ISSUE TITLE
多边形绘制后,使用橡皮擦擦完重新绘制,结果之前被擦掉的又恢复了

### ISSUE THREAD

**Issue by zsedcbm** [whxaxes/canvas-test#4]
http://whxaxes.github.io/canvas-test/src//Other-demo/duobianxing.html
多边形绘制后,使用橡皮擦擦完重新绘制,结果之前被擦掉的又恢复了

**Comment by whxaxes** [comment]
是的，那个是很早很早以前写的demo了，之后就没再管过它了。。。
