### ISSUE TITLE
如果有什么好玩的canvas效果或想法，都可以在这里发，我有空会去研究研究

### ISSUE THREAD

**Issue by whxaxes** [whxaxes/canvas-test#5]
如题

不知不觉就已经好久没更新过什么效果了，不是我懒（误），主要还是工作原因，平时工作中大部分时间都是在写业务代码，所以越来越没空去物色一些好玩的效果来学习。

所以建个issue，如果基(git)友们有什么好玩的canvas效果或想法，并且想知道如何实现，都可以在这里发一下链接或者描述，我会去研究研究，如果研究出来，将在自己的博客上更新相关博文教程。

博客地址：[http://www.cnblogs.com/axes/](http://www.cnblogs.com/axes/)

**Comment by beyondlh** [comment]
威武霸气，先star在fork，找时间学习一下你的例子。canvas刚接触。

**Comment by shenyp09** [comment]
我不太了解canvas，只是最近看到知乎的登录页面的粒子效果，才来看了一下canvas。我试了几个类似的效果实现，发现虽然性能可以达到60帧，但是似乎对占用了过多的性能，基本上实现这种粒子效果就会占满一个核。是因为canvas的限制导致性能不好么？

**Comment by whxaxes** [comment]
@shenyp09  毕竟因为在每一帧中都要对所有粒子进行位置的计算，距离的计算，再加上大量的渲染工作，对cpu的负荷自然也就大了，可以参考这边文章做下优化操作：[canvas最佳实践](http://taobaofed.org/blog/2016/02/22/canvas-performance/)

**Comment by shenyp09** [comment]
这样考虑的话，以这里粒子效应为例，似乎很难进行有效的优化，毕竟需要的计算量在这里摆着。但是另一方面，这个动画确实不是一个非常复杂的动画，是否有其他方式来实现类似的效果？比如svg动画或者css动画？

-- 
Yang Ping, Shen | 谌阳平
Department of Nuclear Physics 
China Institute of Atomic Energy
fermi09@foxmail.com

发件人: Axes <notifications@github.com>
回复: whxaxes/canvas-test <reply@reply.github.com>
日期: 2016年5月17日 at 下午3:58:40
至: whxaxes/canvas-test <canvas-test@noreply.github.com>
抄送: F. Shen Ryan <shenyp09@gmail.com>, Mention <mention@noreply.github.com>
主题:  Re: [whxaxes/canvas-test] 如果有什么好玩的canvas效果或想法，都可以在这里发，我有空会去研究研究 (#5)  

@shenyp09 毕竟因为在每一帧中都要对所有粒子进行位置的计算，距离的计算，再加上大量的渲染工作，对cpu的负荷自然也就大了，可以参考这边文章做下优化操作：canvas最佳实践

**Comment by whxaxes** [comment]
@shenyp09  是的，我此前也想过优化，但是也没想到比较好的优化策略，毕竟我不是写游戏的，算法神马的是短板。
至于svg和css3，在我看来svg和css3更倾向于动画预设，而这种粒子效果要的随机性以及可交互性都需要计算，svg和css3不太适合，如果加入计算的话dom的操作更耗cpu。

**Comment by liuzirui1122** [comment]
小白问一下大神有没有判断当前canvas实际渲染效率或者fps的插件什么的，感觉stats.js不太靠谱。。

**Comment by whxaxes** [comment]
@liuzirui1122  如果你觉得stats.js不靠谱，那就自己算，可参考：http://stackoverflow.com/questions/8279729/calculate-fps-in-canvas-using-requestanimationframe

**Comment by tckxjzc** [comment]
能多点注释，说一下算法就好了- -

**Comment by whxaxes** [comment]
@tckxjzc  大部分效果都是好久以前还是实习生的时候写的，那时也没有写注释的习惯，但是基本上每做一个新效果都会写一篇博文说明一下实现原理，有兴趣的可以看一下：http://www.cnblogs.com/axes/

**Comment by jzp11** [comment]
大神我现在要用canvas做模拟初高中电路实验，刚刚接触连简单的多个图片拖动都不会00有没有简单些的案例让我学学啊

**Comment by carry0987** [comment]
大神，那个黑洞吸引的粒子数量是在哪里控制的??

**Comment by whxaxes** [comment]
@carry0987  https://github.com/whxaxes/canvas-test/blob/master/src/Particle-demo/blackhole/test.coffee#L198

**Comment by carry0987** [comment]
大神我把它改成10000，發現沒有變化欸...
-- 
By Carry

**Comment by carry0987** [comment]
大神，為毛我把重力小丘放到測試服務器上，球變大而且數量變小了?
https://www.nehscsa.com/ball.html

**Comment by leekenky** [comment]
搞一个图片区域选取或裁剪的插件？

**Comment by carry0987** [comment]
@leekenky 早有了..

**Comment by raylhx** [comment]
https://www.canva.com/login/canva
这样的鼠标显示效果是如何实现的呢。只知道一个模糊图片作为背景图，另一张亮色图作为前景图

**Comment by whxaxes** [comment]
@raylhx  就是橡皮擦效果而已：http://whxaxes.github.io/canvas-test/src/Funny-demo/clip/clip.html，他们只是把擦除圈通过透明度改成有渐变效果而已

**Comment by whxaxes** [comment]
现在的自己的技术栈已经不在 canvas 了，先关帖了，有问题的可以单独开 issue
